# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  palprimesapi-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "palprimesapi",
        "-app-port",
        "5221",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
        "-placement-host-address",
        "placement:50006",
        "-log-as-json",
        "true",
        "-log-level",
        "info"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/config/:/config"
    depends_on:
      - palprimesapi
    network_mode: "service:palprimesapi"

  primeapi-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "primeapi",
        "-app-port",
        "5225",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
        "-placement-host-address",
        "placement:50006",
        "-log-as-json",
        "true",
        "-log-level",
        "info"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/config/:/config"
    depends_on:
      - primeapi
    network_mode: "service:primeapi"

  palapi-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "palapi",
        "-app-port",
        "5226",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
        "-placement-host-address",
        "placement:50006",
        "-log-as-json",
        "true",
        "-log-level",
        "info"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/config/:/config"
    depends_on:
      - palapi
    network_mode: "service:palapi"

  placement:
    image: "daprio/dapr"
    command: [ "./placement", "-port", "50006" ]
    ports:
      - "50006:50006"

  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      # To learn about configuring Kafka for access across networks see
      # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
