# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  angularapp:
    image:  angularapp
    build:
      context: src/Frontend/Angular/angular-app
      dockerfile: Dockerfile
    ports:
      - 5220:80
    depends_on:
      - palprimesapi
      - primeapi
      - palapi

  palprimesapi:
    image: palprimesapi
    build:
      context: .
      dockerfile: src/Palprimes.Api/Dockerfile
    ports:
      - 5221:5221

  primeapi:
    image: primeapi
    build:
      context: .
      dockerfile: src/Prime.Api/Dockerfile
    ports:
      - 5225:5225

  palapi:
    image: palapi
    build:
      context: .
      dockerfile: src/Pal.Api/Dockerfile
    ports:
      - 5226:5226
