apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: otel-collector
  namespace: palprimes
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://otel-collector.monitoring.svc.cluster.local:9411/api/v2/spans"
