### Subscribe to notifications
http://localhost:5221/notifications

###
http://localhost:5221/notifications/Subscribe/3b0c4bd6-5141-4a14-95bb-c8a094f51ad0

### Send request
http://localhost:5221/calculation/api/GetCalculations/3b0c4bd6-5141-4a14-95bb-c8a094f51ad0/100


###

http://localhost:5221/dapr/subscribe

###

POST http://localhost:3510/v1.0/publish/pubsub/receivenumber

{
    "Number": 13
}

###

POST http://localhost:3500/v1.0/publish/pubsub/receiveresult

{
    "Number": 13
}
###

POST http://localhost:5221/Pal/receivenumber
Content-Type: application/json

{
    "Number": 10
}

###

dapr publish --publish-app-id palapi --pubsub pubsub --topic receivenumber --data '{"Number": 10}'
