apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: local-elk-cluster
  namespace: monitoring
spec:
  version: 8.1.3
  http:
    tls:
      selfSignedCertificate:
        disabled: true  
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false