apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: local-elk-apm
  namespace: monitoring
spec:
  version: 8.1.3
  http:
    tls:
      selfSignedCertificate:
        disabled: true  
  count: 1
  elasticsearchRef:
    name: local-elk-cluster
  config:
      apm-server:
        capture_personal_data: true
      instrumentation:
        enabled: true
      output:
        elasticsearch:
          hosts: ["local-elk-cluster-es-http:9200"]
      logging.level: info ### enable logging for debug
      logging.to_stderr: true ### output error if any
      logging.metrics.enabled: true    